## Append samples you want in your CSV to this file as resources ##
resources:
- namespace.yaml
- ignored-namespace.yaml
- managed-kube-namespace.yaml
- secret.yaml
- ignored-secret.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
