resources:
- bases/config.yaml
patchesJson6902:
- path: patches/olm.config.yaml
  target:
    group: scorecard.operatorframework.io
    version: v1alpha3
    kind: Configuration
    name: config
#+kubebuilder:scaffold:patchesJson6902
