# Copyright (c) 2022, Nadun De Silva. All Rights Reserved.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#   http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vscode-wildcard
spec:
  isCA: false
  commonName: '*.vscode.local'
  dnsNames:
  - vscode.local
  - '*.vscode.local'
  subject:
    organizations:
      - k8s-replicator.nadundesilva.github.io
  usages:
  - server auth
  duration: 720h
  renewBefore: 360h
  secretName: vscode-wildcard-tls
  secretTemplate:
    labels:
      k8s-replicator.nadundesilva.github.io/object-type: replicated
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: ca
    kind: Issuer
    group: cert-manager.io
