name: Check PR

on:
    pull_request:
        branches:
            - main

jobs:
    run-super-linter:
        name: Run GitHub Super Linter
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Lint Code Base
              uses: github/super-linter@v4
              env:
                  DEFAULT_BRANCH: main
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  VALIDATE_ALL_CODEBASE: "true"
                  VALIDATE_GO: "false"
                  KUBERNETES_KUBEVAL_OPTIONS: "--ignore-missing-schemas"

    run-golangci-lint:
        name: Run GoLangCI Lint
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Setup GoLang
              uses: actions/setup-go@v2
              with:
                  go-version: "^1.18"
            - name: Install Dependencies
              run: |
                  go get ./...
                  go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.44.2
            - name: Lint Go Code
              run: |
                golangci-lint run -c .github/linters/.golangci.yml --timeout 2m

    run-codeql-analysis:
        name: Run CodeQL Analysis
        runs-on: ubuntu-latest
        permissions:
            actions: read
            contents: read
            security-events: write
        strategy:
            fail-fast: false
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Initialize CodeQL
              uses: github/codeql-action/init@v1
              with:
                  languages: go
            - name: Autobuild
              uses: github/codeql-action/autobuild@v1
            - name: Perform CodeQL Analysis
              uses: github/codeql-action/analyze@v1

    run-e2e-tests:
        name: Run E2E Tests
        runs-on: ubuntu-latest
        strategy:
            matrix:
                resource:
                    - secret
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Setup GoLang
              uses: actions/setup-go@v2
              with:
                  go-version: "^1.18"
            - name: Run E2E Tests
              run: make test.e2e
              env:
                  TEST_FLAGS: "-args --labels \"resource=${{ matrix.resource }}\""
                  CONTROLLER_IMAGE: nadunrds/k8s-replicator:${{ github.sha }}

    run-trivy-scan:
        name: Run Trivy Scan
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Setup GoLang
              uses: actions/setup-go@v2
              with:
                  go-version: "^1.18"
            - name: Building Controller
              run: make all
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1
            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v1
              with:
                  install: true
            - name: Available platforms
              run: echo ${{ steps.buildx.outputs.platforms }}
            - name: Build Docker Image for scanning
              uses: docker/build-push-action@v2
              with:
                  context: .
                  load: true
                  tags: nadunrds/k8s-replicator:${{ github.sha }}
            - name: Run Trivy vulnerability scanner
              uses: aquasecurity/trivy-action@master
              with:
                  image-ref: nadunrds/k8s-replicator:${{ github.sha }}
                  format: 'table'
                  exit-code: '1'
                  ignore-unfixed: true
