name: Main Branch Build

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: read

jobs:
  build:
    name: Build Main Branch
    uses: ./.github/workflows/build.yaml
    with:
      version: 0.0.0-${{ github.ref_name }}
      publish-artifacts: true
    permissions:
      contents: read
      packages: read
      security-events: write
      checks: write
      statuses: write
    secrets:
      docker-hub-token: ${{ secrets.DOCKER_HUB_TOKEN }}
