name: Main Branch Build

on:
    push:
        branches:
            - main

jobs:
    build:
        name: Build Main Branch
        uses: ./.github/workflows/build.yaml
        with:
            version: 0.0.0-${{ github.ref_name }}
            publish-artifacts: true
        secrets:
            docker-hub-token: ${{ secrets.DOCKER_HUB_TOKEN }}
