name: Scan for Vulnerabilities

on:
    schedule:
        - cron: '0 0 * * *'
    workflow_dispatch:

jobs:
    run-trivy-scan:
        name: Run Trivy Scan
        runs-on: ubuntu-latest
        steps:
            - name: Run Trivy vulnerability scanner
              uses: aquasecurity/trivy-action@master
              with:
                  image-ref: nadunrds/k8s-replicator:latest
                  format: 'table'
                  exit-code: '1'
                  ignore-unfixed: true
